# Generated by Django 2.0 on 2020-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='登录用户')),
                ('name_yu', models.CharField(max_length=20, verbose_name='域')),
                ('computer_name', models.CharField(max_length=100, verbose_name='计算机名')),
                ('system_type', models.CharField(max_length=100, verbose_name='系统类型')),
                ('c_cpu', models.CharField(max_length=100, verbose_name='CPU')),
                ('c_memory', models.CharField(max_length=100, verbose_name='内存')),
                ('c_network', models.CharField(max_length=100, verbose_name='IP地址')),
                ('c_display', models.CharField(max_length=100, verbose_name='显卡')),
                ('c_date', models.CharField(max_length=100, verbose_name='硬盘')),
                ('mac_network', models.DateTimeField(max_length=100, verbose_name='MAC地址')),
                ('it_number', models.DateTimeField(max_length=100, verbose_name='IT资产编号', blank=True)),
                ('seat_number', models.CharField(max_length=100, verbose_name='座位编号')),
                ('asset_users', models.CharField(max_length=100, verbose_name='资产使用者')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),

            ],
        ),
        migrations.AlterUniqueTogether(
            name='computer_status',
            unique_together={('name', 'computer_name','mac_network')},
        ),
    ]
