# Generated by Django 2.0 on 2020-06-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer_status',
            options={'managed': True},
        ),
    ]
