# Generated by Django 2.0 on 2020-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20200624_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_status',
            name='it_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='IT资产编号'),
        ),
        migrations.AlterField(
            model_name='computer_status',
            name='mac_network',
            field=models.CharField(max_length=100, verbose_name='MAC地址'),
        ),
        migrations.AlterUniqueTogether(
            name='computer_status',
            unique_together={('name', 'computer_name', 'mac_network')},
        ),
    ]
