# Generated by Django 2.0 on 2020-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20200701_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=20, verbose_name='协议类型')),
                ('address', models.CharField(max_length=20, verbose_name='IP地址')),
                ('min', models.CharField(max_length=20, verbose_name='延迟时间')),
                ('ip_mac', models.CharField(max_length=20, verbose_name='MAC地址')),
                ('ip_type', models.CharField(max_length=20, verbose_name='类型')),
                ('interface', models.CharField(max_length=20, verbose_name='接口地址')),
            ],
        ),
        migrations.AlterField(
            model_name='computer_status',
            name='asset_users',
            field=models.CharField(blank=True, max_length=100, verbose_name='资产使用者'),
        ),
        migrations.AlterField(
            model_name='computer_status',
            name='seat_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='座位编号'),
        ),
    ]
