# Generated by Django 2.0 on 2020-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20200825_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_inspect',
            name='in_flag',
            field=models.CharField(blank=True, max_length=10, verbose_name='确认标志'),
        ),
    ]
