# Generated by Django 2.0 on 2020-08-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_number_inspect_in_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_inspect',
            name='in_time',
            field=models.DateTimeField(blank=True, max_length=100, verbose_name='更新时间'),
        ),
    ]
