# Generated by Django 2.0 on 2020-08-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_auto_20200825_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number_inspect',
        ),
    ]
