# Generated by Django 2.0 on 2020-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_delete_number_inspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.CharField(blank=True, max_length=100, verbose_name='数据表序列')),
                ('tab_name', models.CharField(blank=True, max_length=100, verbose_name='数据表名称')),
            ],
        ),
    ]
