# Generated by Django 2.0 on 2020-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0009_number_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_table',
            name='tab_number',
            field=models.IntegerField(blank=True, verbose_name='数据表序列'),
        ),
    ]
