# Generated by Django 2.0 on 2020-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_auto_20200825_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='number_table',
            name='tab_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='数据表序列'),
        ),
    ]
