# Generated by Django 2.0 on 2020-08-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0021_auto_20200826_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number_table',
        ),
    ]
