# Generated by Django 2.0 on 2020-08-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0023_number_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='number_table',
        ),
    ]
